"""empty message

Revision ID: 103dfa5897a7
Revises: ffdc0a98111c
Create Date: 2023-01-03 21:40:25.951453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103dfa5897a7'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shop_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_img', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('zipcode', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['zipcode'])
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.create_unique_constraint(None, 'users', ['profile_img'])
    op.create_unique_constraint(None, 'users', ['shop_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'zipcode')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'profile_img')
    op.drop_column('users', 'shop_name')
    # ### end Alembic commands ###