"""adjusted for average review

Revision ID: 7c636bc2967c
Revises: 884229f57545
Create Date: 2023-01-04 10:55:05.560695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c636bc2967c'
down_revision = '884229f57545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'avg_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('avg_rating', sa.NUMERIC(), nullable=False))
    # ### end Alembic commands ###
